import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1737304868666 implements MigrationInterface {
    name = 'InitialMigration1737304868666'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."student_grade_type_enum" AS ENUM('year', 'turm_1', 'turm_2', 'ongoing')`);
        await queryRunner.query(`CREATE TYPE "public"."student_grade_gradewithwords_enum" AS ENUM('0', '1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "student_grade" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "message" text NOT NULL, "type" "public"."student_grade_type_enum" NOT NULL DEFAULT 'ongoing', "grade" integer NOT NULL, "gradeWithWords" "public"."student_grade_gradewithwords_enum" NOT NULL DEFAULT '4', "fromUserId" uuid, "studentId" uuid, "subjectId" uuid, CONSTRAINT "PK_241487af7c8a29186b0d46c1223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "REL_a51bd21a6e90dbe656ad65cab8" UNIQUE ("userId"), CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "filename" text NOT NULL, "cloudFilename" text NOT NULL, "messageId" uuid, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startDate" TIMESTAMP, "prevEducation" text NOT NULL DEFAULT 'none', "token" text NOT NULL DEFAULT '', "recordMessage" text, "userId" uuid, "classId" uuid, CONSTRAINT "REL_b35463776b4a11a3df3c30d920" UNIQUE ("userId"), CONSTRAINT "PK_3d8016e1cb58429474a3c041904" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_dossier" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "message" text NOT NULL, "fromUserId" uuid, "studentId" uuid, "subjectId" uuid, CONSTRAINT "PK_161dfe33f6a1cae7ee7b99c9f9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('admin', 'parent', 'student', 'teacher', 'viewer')`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('active', 'inactive', 'blocked', 'unverified')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstName" text NOT NULL, "middleName" text NOT NULL, "lastName" text NOT NULL, "email" text NOT NULL, "password" text NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'viewer', "registerToken" text, "status" "public"."user_status_enum" NOT NULL DEFAULT 'unverified', "institutionId" uuid, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_assignmenttype_enum" AS ENUM('homework', 'classwork', 'exam')`);
        await queryRunner.query(`CREATE TYPE "public"."message_messagetype_enum" AS ENUM('assignment', 'message')`);
        await queryRunner.query(`CREATE TYPE "public"."message_status_enum" AS ENUM('created', 'published')`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "assignmentType" "public"."message_assignmenttype_enum", "data" text, "messageType" "public"."message_messagetype_enum" NOT NULL, "status" "public"."message_status_enum" NOT NULL DEFAULT 'created', "assignmentDueDate" TIMESTAMP, "fromUserId" uuid, "subjectId" uuid, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."class_tokenstatus_enum" AS ENUM('0', '1')`);
        await queryRunner.query(`CREATE TABLE "class" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "startYear" smallint NOT NULL, "endYear" smallint NOT NULL, "totalStudentCount" smallint NOT NULL, "letter" text NOT NULL, "number" smallint NOT NULL, "token" text NOT NULL DEFAULT '', "tokenStatus" "public"."class_tokenstatus_enum" NOT NULL DEFAULT '0', "institutionId" uuid, "teacherId" uuid, CONSTRAINT "UQ_a996c5bc6b48355f9994fdad341" UNIQUE ("letter", "number"), CONSTRAINT "REL_d3e7278501fe8c5e8cf2cf74be" UNIQUE ("teacherId"), CONSTRAINT "PK_0b9024d21bdfba8b1bd1c300eae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startYear" smallint NOT NULL, "endYear" smallint NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "institutionId" uuid, "classId" uuid, "messagesId" uuid, CONSTRAINT "PK_12eee115462e38d62e5455fc054" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."institution_type_enum" AS ENUM('natural_mathematical', 'technological', 'linguistical', 'mathematical', 'humanitarian', 'art', 'su', 'ou')`);
        await queryRunner.query(`CREATE TYPE "public"."institution_educationalstage_enum" AS ENUM('elementary', 'primary', 'united', 'high')`);
        await queryRunner.query(`CREATE TABLE "institution" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "email" text NOT NULL, "type" "public"."institution_type_enum" NOT NULL, "educationalStage" "public"."institution_educationalstage_enum" NOT NULL, "alias" text NOT NULL, CONSTRAINT "UQ_d218ad3566afa9e396f184fd7d5" UNIQUE ("name"), CONSTRAINT "UQ_43c747addb41aeac8b1da0c58d5" UNIQUE ("email"), CONSTRAINT "UQ_899ffe9da666367e93f96ee4eea" UNIQUE ("alias"), CONSTRAINT "PK_f60ee4ff0719b7df54830b39087" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_day_enum" AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')`);
        await queryRunner.query(`CREATE TABLE "schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "day" "public"."schedule_day_enum" NOT NULL, "room" text NOT NULL, "subjectId" uuid, "classId" uuid, "institutionId" uuid, CONSTRAINT "UQ_0d58136878eacf57c2f2cf4012f" UNIQUE ("institutionId", "day", "subjectId", "classId", "startTime", "endTime"), CONSTRAINT "PK_1c05e42aec7371641193e180046" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teacher_contracttype_enum" AS ENUM('part_time', 'full_time')`);
        await queryRunner.query(`CREATE TABLE "teacher" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "education" text, "yearsExperience" smallint, "contractType" "public"."teacher_contracttype_enum", "token" text NOT NULL DEFAULT '', "userId" uuid, CONSTRAINT "REL_4f596730e16ee49d9b081b5d8e" UNIQUE ("userId"), CONSTRAINT "PK_2f807294148612a9751dacf1026" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parent_student" ("parent" uuid NOT NULL, "student" uuid NOT NULL, CONSTRAINT "PK_4170a51ea250bbba2e96b50f031" PRIMARY KEY ("parent", "student"))`);
        await queryRunner.query(`CREATE INDEX "IDX_29075d4c562cb3f9387bfa018c" ON "parent_student" ("parent") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6e2338394f8824bb2542d53fe" ON "parent_student" ("student") `);
        await queryRunner.query(`CREATE TABLE "student_record_files" ("student" uuid NOT NULL, "file" uuid NOT NULL, CONSTRAINT "PK_087a8f12512c7a70b2ee21d722a" PRIMARY KEY ("student", "file"))`);
        await queryRunner.query(`CREATE INDEX "IDX_493edd9a7e5d7ae118d961383c" ON "student_record_files" ("student") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e462245c47455641c6685cdcf" ON "student_record_files" ("file") `);
        await queryRunner.query(`CREATE TABLE "student_dossier_files" ("dossier" uuid NOT NULL, "file" uuid NOT NULL, CONSTRAINT "PK_a86b3dce0810223884038871e82" PRIMARY KEY ("dossier", "file"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9a1fced041906c790d7fdabba" ON "student_dossier_files" ("dossier") `);
        await queryRunner.query(`CREATE INDEX "IDX_ddefaa3b16ae92bad9c2078723" ON "student_dossier_files" ("file") `);
        await queryRunner.query(`CREATE TABLE "message_toUsers" ("message" uuid NOT NULL, "user" uuid NOT NULL, CONSTRAINT "PK_39ddab38f0d3724857d4da869d3" PRIMARY KEY ("message", "user"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0aad461e5905079b03c8a59378" ON "message_toUsers" ("message") `);
        await queryRunner.query(`CREATE INDEX "IDX_23dae1a3c64a2397705cf6514c" ON "message_toUsers" ("user") `);
        await queryRunner.query(`CREATE TABLE "message_toClass" ("message" uuid NOT NULL, "class" uuid NOT NULL, CONSTRAINT "PK_3ee1697d9afb25ce29c8e597c73" PRIMARY KEY ("message", "class"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a92b3cfceb8305fc25551fddcf" ON "message_toClass" ("message") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b0466a321422f71c266d23669" ON "message_toClass" ("class") `);
        await queryRunner.query(`CREATE TABLE "teacher_subject" ("subjects" uuid NOT NULL, "teachers" uuid NOT NULL, CONSTRAINT "PK_bca80940b18042cdd5c39b48ab3" PRIMARY KEY ("subjects", "teachers"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d3cc8020891fc8cdc8c8307b8c" ON "teacher_subject" ("subjects") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b4ee467ff4113a8aa2517591f" ON "teacher_subject" ("teachers") `);
        await queryRunner.query(`CREATE TABLE "schedule_teacher" ("schedule" uuid NOT NULL, "teacher" uuid NOT NULL, CONSTRAINT "PK_ad472d6d4b903648373e15ff42f" PRIMARY KEY ("schedule", "teacher"))`);
        await queryRunner.query(`CREATE INDEX "IDX_55c95fa0767b1b6636eccaf6eb" ON "schedule_teacher" ("schedule") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f2d9eaac5fa05e1f52569eac5" ON "schedule_teacher" ("teacher") `);
        await queryRunner.query(`ALTER TABLE "student_grade" ADD CONSTRAINT "FK_bb2a78057d1056a69a223be64f1" FOREIGN KEY ("fromUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_grade" ADD CONSTRAINT "FK_2bc4f1801ff5bd70b8a799626ae" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_grade" ADD CONSTRAINT "FK_68759787c8e6a1a18d22a2b20d8" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent" ADD CONSTRAINT "FK_a51bd21a6e90dbe656ad65cab89" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file" ADD CONSTRAINT "FK_a78a68c3f577a485dd4c741909f" FOREIGN KEY ("messageId") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student" ADD CONSTRAINT "FK_b35463776b4a11a3df3c30d920a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student" ADD CONSTRAINT "FK_bd5c8f2ef67394162384a484ba1" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_dossier" ADD CONSTRAINT "FK_618ab26bd69141bfb3c449e9be8" FOREIGN KEY ("fromUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_dossier" ADD CONSTRAINT "FK_17501ddbda8ce8f3163a8f5e5b4" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_dossier" ADD CONSTRAINT "FK_9852b2043d8111cb5d12a095d11" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ca0de218397aed2409d865d1580" FOREIGN KEY ("institutionId") REFERENCES "institution"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_c59262513a3006fd8f58bb4b7c2" FOREIGN KEY ("fromUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_90f162a0d728ff62e18f23646a2" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "FK_dfd2f9066e412257415d2376c63" FOREIGN KEY ("institutionId") REFERENCES "institution"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "FK_d3e7278501fe8c5e8cf2cf74be7" FOREIGN KEY ("teacherId") REFERENCES "teacher"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject" ADD CONSTRAINT "FK_6ce29d082752b69b91f64c4e65d" FOREIGN KEY ("institutionId") REFERENCES "institution"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject" ADD CONSTRAINT "FK_bd8702647b256adaa5bb5321565" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject" ADD CONSTRAINT "FK_8619e4246b4f695fda4c971a500" FOREIGN KEY ("messagesId") REFERENCES "message"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_9fa71efc605659e54dec60bf17e" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_08aac4a7aad6819197a8ba8f3e8" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_a6d06452061e23ac52553245b46" FOREIGN KEY ("institutionId") REFERENCES "institution"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher" ADD CONSTRAINT "FK_4f596730e16ee49d9b081b5d8e5" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_student" ADD CONSTRAINT "FK_29075d4c562cb3f9387bfa018c9" FOREIGN KEY ("parent") REFERENCES "parent"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "parent_student" ADD CONSTRAINT "FK_a6e2338394f8824bb2542d53fe6" FOREIGN KEY ("student") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_record_files" ADD CONSTRAINT "FK_493edd9a7e5d7ae118d961383cf" FOREIGN KEY ("student") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_record_files" ADD CONSTRAINT "FK_9e462245c47455641c6685cdcfc" FOREIGN KEY ("file") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_dossier_files" ADD CONSTRAINT "FK_f9a1fced041906c790d7fdabbad" FOREIGN KEY ("dossier") REFERENCES "student_dossier"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_dossier_files" ADD CONSTRAINT "FK_ddefaa3b16ae92bad9c2078723d" FOREIGN KEY ("file") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_toUsers" ADD CONSTRAINT "FK_0aad461e5905079b03c8a593782" FOREIGN KEY ("message") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "message_toUsers" ADD CONSTRAINT "FK_23dae1a3c64a2397705cf6514c0" FOREIGN KEY ("user") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_toClass" ADD CONSTRAINT "FK_a92b3cfceb8305fc25551fddcf0" FOREIGN KEY ("message") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "message_toClass" ADD CONSTRAINT "FK_2b0466a321422f71c266d236695" FOREIGN KEY ("class") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" ADD CONSTRAINT "FK_d3cc8020891fc8cdc8c8307b8cf" FOREIGN KEY ("subjects") REFERENCES "subject"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" ADD CONSTRAINT "FK_0b4ee467ff4113a8aa2517591f7" FOREIGN KEY ("teachers") REFERENCES "teacher"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_teacher" ADD CONSTRAINT "FK_55c95fa0767b1b6636eccaf6eb1" FOREIGN KEY ("schedule") REFERENCES "schedule"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "schedule_teacher" ADD CONSTRAINT "FK_6f2d9eaac5fa05e1f52569eac5e" FOREIGN KEY ("teacher") REFERENCES "teacher"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "schedule_teacher" DROP CONSTRAINT "FK_6f2d9eaac5fa05e1f52569eac5e"`);
        await queryRunner.query(`ALTER TABLE "schedule_teacher" DROP CONSTRAINT "FK_55c95fa0767b1b6636eccaf6eb1"`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" DROP CONSTRAINT "FK_0b4ee467ff4113a8aa2517591f7"`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" DROP CONSTRAINT "FK_d3cc8020891fc8cdc8c8307b8cf"`);
        await queryRunner.query(`ALTER TABLE "message_toClass" DROP CONSTRAINT "FK_2b0466a321422f71c266d236695"`);
        await queryRunner.query(`ALTER TABLE "message_toClass" DROP CONSTRAINT "FK_a92b3cfceb8305fc25551fddcf0"`);
        await queryRunner.query(`ALTER TABLE "message_toUsers" DROP CONSTRAINT "FK_23dae1a3c64a2397705cf6514c0"`);
        await queryRunner.query(`ALTER TABLE "message_toUsers" DROP CONSTRAINT "FK_0aad461e5905079b03c8a593782"`);
        await queryRunner.query(`ALTER TABLE "student_dossier_files" DROP CONSTRAINT "FK_ddefaa3b16ae92bad9c2078723d"`);
        await queryRunner.query(`ALTER TABLE "student_dossier_files" DROP CONSTRAINT "FK_f9a1fced041906c790d7fdabbad"`);
        await queryRunner.query(`ALTER TABLE "student_record_files" DROP CONSTRAINT "FK_9e462245c47455641c6685cdcfc"`);
        await queryRunner.query(`ALTER TABLE "student_record_files" DROP CONSTRAINT "FK_493edd9a7e5d7ae118d961383cf"`);
        await queryRunner.query(`ALTER TABLE "parent_student" DROP CONSTRAINT "FK_a6e2338394f8824bb2542d53fe6"`);
        await queryRunner.query(`ALTER TABLE "parent_student" DROP CONSTRAINT "FK_29075d4c562cb3f9387bfa018c9"`);
        await queryRunner.query(`ALTER TABLE "teacher" DROP CONSTRAINT "FK_4f596730e16ee49d9b081b5d8e5"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_a6d06452061e23ac52553245b46"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_08aac4a7aad6819197a8ba8f3e8"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_9fa71efc605659e54dec60bf17e"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP CONSTRAINT "FK_8619e4246b4f695fda4c971a500"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP CONSTRAINT "FK_bd8702647b256adaa5bb5321565"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP CONSTRAINT "FK_6ce29d082752b69b91f64c4e65d"`);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "FK_d3e7278501fe8c5e8cf2cf74be7"`);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "FK_dfd2f9066e412257415d2376c63"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_90f162a0d728ff62e18f23646a2"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_c59262513a3006fd8f58bb4b7c2"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ca0de218397aed2409d865d1580"`);
        await queryRunner.query(`ALTER TABLE "student_dossier" DROP CONSTRAINT "FK_9852b2043d8111cb5d12a095d11"`);
        await queryRunner.query(`ALTER TABLE "student_dossier" DROP CONSTRAINT "FK_17501ddbda8ce8f3163a8f5e5b4"`);
        await queryRunner.query(`ALTER TABLE "student_dossier" DROP CONSTRAINT "FK_618ab26bd69141bfb3c449e9be8"`);
        await queryRunner.query(`ALTER TABLE "student" DROP CONSTRAINT "FK_bd5c8f2ef67394162384a484ba1"`);
        await queryRunner.query(`ALTER TABLE "student" DROP CONSTRAINT "FK_b35463776b4a11a3df3c30d920a"`);
        await queryRunner.query(`ALTER TABLE "file" DROP CONSTRAINT "FK_a78a68c3f577a485dd4c741909f"`);
        await queryRunner.query(`ALTER TABLE "parent" DROP CONSTRAINT "FK_a51bd21a6e90dbe656ad65cab89"`);
        await queryRunner.query(`ALTER TABLE "student_grade" DROP CONSTRAINT "FK_68759787c8e6a1a18d22a2b20d8"`);
        await queryRunner.query(`ALTER TABLE "student_grade" DROP CONSTRAINT "FK_2bc4f1801ff5bd70b8a799626ae"`);
        await queryRunner.query(`ALTER TABLE "student_grade" DROP CONSTRAINT "FK_bb2a78057d1056a69a223be64f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f2d9eaac5fa05e1f52569eac5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55c95fa0767b1b6636eccaf6eb"`);
        await queryRunner.query(`DROP TABLE "schedule_teacher"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b4ee467ff4113a8aa2517591f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3cc8020891fc8cdc8c8307b8c"`);
        await queryRunner.query(`DROP TABLE "teacher_subject"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b0466a321422f71c266d23669"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a92b3cfceb8305fc25551fddcf"`);
        await queryRunner.query(`DROP TABLE "message_toClass"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23dae1a3c64a2397705cf6514c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0aad461e5905079b03c8a59378"`);
        await queryRunner.query(`DROP TABLE "message_toUsers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddefaa3b16ae92bad9c2078723"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9a1fced041906c790d7fdabba"`);
        await queryRunner.query(`DROP TABLE "student_dossier_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e462245c47455641c6685cdcf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_493edd9a7e5d7ae118d961383c"`);
        await queryRunner.query(`DROP TABLE "student_record_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6e2338394f8824bb2542d53fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29075d4c562cb3f9387bfa018c"`);
        await queryRunner.query(`DROP TABLE "parent_student"`);
        await queryRunner.query(`DROP TABLE "teacher"`);
        await queryRunner.query(`DROP TYPE "public"."teacher_contracttype_enum"`);
        await queryRunner.query(`DROP TABLE "schedule"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_day_enum"`);
        await queryRunner.query(`DROP TABLE "institution"`);
        await queryRunner.query(`DROP TYPE "public"."institution_educationalstage_enum"`);
        await queryRunner.query(`DROP TYPE "public"."institution_type_enum"`);
        await queryRunner.query(`DROP TABLE "subject"`);
        await queryRunner.query(`DROP TABLE "class"`);
        await queryRunner.query(`DROP TYPE "public"."class_tokenstatus_enum"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TYPE "public"."message_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_messagetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_assignmenttype_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "student_dossier"`);
        await queryRunner.query(`DROP TABLE "student"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "parent"`);
        await queryRunner.query(`DROP TABLE "student_grade"`);
        await queryRunner.query(`DROP TYPE "public"."student_grade_gradewithwords_enum"`);
        await queryRunner.query(`DROP TYPE "public"."student_grade_type_enum"`);
    }

}
